/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#fabd00",
        "primary-container": "#ff544c",
        "on-secondary": "#003063",
        "surface-dim": "#111316",
        "on-tertiary-fixed": "#261a00",
        "on-error-container": "#ffdad6",
        "secondary": "#a9c7ff",
        "surface-bright": "#37393d",
        "surface-container-high": "#282a2d",
        "secondary-container": "#005db7",
        "on-primary-container": "#5c0005",
        "background": "#111316",
        "surface-container": "#1e2023",
        "surface-container-highest": "#333538",
        "on-secondary-container": "#c6d9ff",
        "outline-variant": "#3a3d42",
        "secondary-fixed-dim": "#a9c7ff",
        "tertiary": "#fabd00",
        "surface": "#111316",
        "primary-fixed-dim": "#ffb4ac",
        "on-primary": "#690006",
        "on-primary-fixed-variant": "#93000d",
        "surface-variant": "#333538",
        "outline": "#8d9199",
        "error": "#ffb4ab",
        "secondary-fixed": "#d6e3ff",
        "on-surface": "#e2e2e6",
        "on-background": "#e2e2e6",
        "on-tertiary-fixed-variant": "#5b4300",
        "tertiary-fixed": "#ffdf9e",
        "on-surface-variant": "#c4c7cf",
        "inverse-on-surface": "#2f3034",
        "primary-fixed": "#ffdad6",
        "inverse-primary": "#bb171c",
        "on-tertiary": "#3f2e00",
        "on-primary-fixed": "#410002",
        "on-tertiary-container": "#372700",
        "inverse-surface": "#e2e2e6",
        "surface-container-lowest": "#0c0e11",
        "error-container": "#93000a",
        "primary": "#ffb4ac",
        "surface-tint": "#ffb4ac",
        "surface-container-low": "#1a1c1f",
        "on-error": "#690005",
        "on-secondary-fixed": "#001b3d",
        "tertiary-container": "#b78a00",
        "on-secondary-fixed-variant": "#00468c"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "20px",
        "md": "24px",
        "margin-desktop": "48px",
        "sm": "16px",
        "base": "4px",
        "xl": "64px",
        "lg": "40px",
        "xs": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Geist", "monospace"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
